# Configuration for dbt data model UI

# Path to the dbt project directory (relative to this config file or absolute)
dbt_project_path: "./dbt_concept"
# dbt_project_path: "./dbt_built"

# Path to the dbt manifest.json (relative to dbt_project_path or absolute)
dbt_manifest_path: "target/manifest.json"

# Path to the dbt catalog.json (relative to dbt_project_path or absolute)
dbt_catalog_path: "target/catalog.json"

# Path where the data model YAML will be saved (relative to dbt_project_path or absolute)
data_model_file: "data_model.yml"

# List of path patterns to include (filters dbt models by original_file_path)
# If empty, all models are included.
dbt_model_paths:
  - "3_core"

